Update 9.1 schedule for 2Q
eclipse-ee4j/jakartaee-platform pull request #314
Opened 2021-03-10 19:24 UTC by kwsutter

Signed-off-by: Kevin Sutter <kwsutter@gmail.com>

Updated 9.1 schedule with 2Q information.  Also, updated the FAQ with references to Ops Guide definition of Service Release process.

2021-03-11 07:38 UTC, ivargrimstad requested changes

2021-03-11 07:38 UTC, ivargrimstad commented on jakartaee9/JakartaEE9.1.md
> + - [Glassfish 6.2 M1](tbd)
Isn't it 6.1 M1?

2021-03-16 15:16 UTC, kwsutter commented on jakartaee9/JakartaEE9.1.md
> + - [Glassfish 6.2 M1](tbd)
Yes, of course.

2021-03-16 16:07 UTC, ivargrimstad approved these changes

2021-03-16 19:21 UTC, merged